export const FETCH_USER = "FETCH_USER";
export const FETCH_LISTINGS = "FETCH_LISTINGS";
export const FETCH_LISTING = "FETCH_LISTING";
export const CREATE_LISTING = "CREATE_LISTING";
export const DELETE_LISTING = "DELETE_LISTING";
export const EDIT_LISTING = "EDIT_LISTING";
export const CHANGE_THEME = "CHANGE_THEME";
export const GET_THEME = "GET_THEME";
