export const roleOptions = [
  {
    key: "Top",
    text: "Top",
    value: "Top",
    image: { avatar: true, src: "/images/roles/top.png" },
  },
  {
    key: "Jungle",
    text: "Jungle",
    value: "Jungle",
    image: { avatar: true, src: "/images/roles/jungle.png" },
  },
  {
    key: "Mid",
    text: "Mid",
    value: "Mid",
    image: { avatar: false, src: "/images/roles/mid.png" },
  },
  {
    key: "Support",
    text: "Support",
    value: "Support",
    image: { avatar: true, src: "/images/roles/support.png" },
  },
  {
    key: "Bot",
    text: "Bot",
    value: "Bot",
    image: { avatar: true, src: "/images/roles/bot.png" },
  },
];

export const championOptions = [
  {
    key: "Aatrox",
    text: "Aatrox",
    value: "Aatrox",
    image: { avatar: true, src: "/images/champions/Aatrox.png" },
  },
  {
    key: "Ahri",
    text: "Ahri",
    value: "Ahri",
    image: { avatar: true, src: "/images/champions/Ahri.png" },
  },
  {
    key: "Akali",
    text: "Akali",
    value: "Akali",
    image: { avatar: true, src: "/images/champions/Akali.png" },
  },
  {
    key: "Alistar",
    text: "Alistar",
    value: "Alistar",
    image: { avatar: true, src: "/images/champions/Alistar.png" },
  },
  {
    key: "Amumu",
    text: "Amumu",
    value: "Amumu",
    image: { avatar: true, src: "/images/champions/Amumu.png" },
  },
  {
    key: "Anivia",
    text: "Anivia",
    value: "Anivia",
    image: { avatar: true, src: "/images/champions/Anivia.png" },
  },
  {
    key: "Annie",
    text: "Annie",
    value: "Annie",
    image: { avatar: true, src: "/images/champions/Annie.png" },
  },
  {
    key: "Aphelios",
    text: "Aphelios",
    value: "Aphelios",
    image: { avatar: true, src: "/images/champions/Aphelios.png" },
  },
  {
    key: "Ashe",
    text: "Ashe",
    value: "Ashe",
    image: { avatar: true, src: "/images/champions/Ashe.png" },
  },
  {
    key: "AurelionSol",
    text: "AurelionSol",
    value: "AurelionSol",
    image: { avatar: true, src: "/images/champions/AurelionSol.png" },
  },
  {
    key: "Azir",
    text: "Azir",
    value: "Azir",
    image: { avatar: true, src: "/images/champions/Azir.png" },
  },
  {
    key: "Bard",
    text: "Bard",
    value: "Bard",
    image: { avatar: true, src: "/images/champions/Bard.png" },
  },
  {
    key: "Blitzcrank",
    text: "Blitzcrank",
    value: "Blitzcrank",
    image: { avatar: true, src: "/images/champions/Blitzcrank.png" },
  },
  {
    key: "Brand",
    text: "Brand",
    value: "Brand",
    image: { avatar: true, src: "/images/champions/Brand.png" },
  },
  {
    key: "Braum",
    text: "Braum",
    value: "Braum",
    image: { avatar: true, src: "/images/champions/Braum.png" },
  },
  {
    key: "Caitlyn",
    text: "Caitlyn",
    value: "Caitlyn",
    image: { avatar: true, src: "/images/champions/Caitlyn.png" },
  },
  {
    key: "Camille",
    text: "Camille",
    value: "Camille",
    image: { avatar: true, src: "/images/champions/Camille.png" },
  },
  {
    key: "Cassiopeia",
    text: "Cassiopeia",
    value: "Cassiopeia",
    image: { avatar: true, src: "/images/champions/Cassiopeia.png" },
  },
  {
    key: "ChoGath",
    text: "ChoGath",
    value: "ChoGath",
    image: { avatar: true, src: "/images/champions/ChoGath.png" },
  },
  {
    key: "Corki",
    text: "Corki",
    value: "Corki",
    image: { avatar: true, src: "/images/champions/Corki.png" },
  },
  {
    key: "Darius",
    text: "Darius",
    value: "Darius",
    image: { avatar: true, src: "/images/champions/Darius.png" },
  },
  {
    key: "Diana",
    text: "Diana",
    value: "Diana",
    image: { avatar: true, src: "/images/champions/Diana.png" },
  },
  {
    key: "Draven",
    text: "Draven",
    value: "Draven",
    image: { avatar: true, src: "/images/champions/Draven.png" },
  },
  {
    key: "Dr.Mundo",
    text: "Dr.Mundo",
    value: "Dr.Mundo",
    image: { avatar: true, src: "/images/champions/DrMundo.png" },
  },
  {
    key: "Ekko",
    text: "Ekko",
    value: "Ekko",
    image: { avatar: true, src: "/images/champions/Ekko.png" },
  },
  {
    key: "Elise",
    text: "Elise",
    value: "Elise",
    image: { avatar: true, src: "/images/champions/Elise.png" },
  },
  {
    key: "Evelynn",
    text: "Evelynn",
    value: "Evelynn",
    image: { avatar: true, src: "/images/champions/Evelynn.png" },
  },
  {
    key: "Ezreal",
    text: "Ezreal",
    value: "Ezreal",
    image: { avatar: true, src: "/images/champions/Ezreal.png" },
  },
  {
    key: "Fiddlesticks",
    text: "Fiddlesticks",
    value: "Fiddlesticks",
    image: { avatar: true, src: "/images/champions/Fiddlesticks.png" },
  },
  {
    key: "Fiora",
    text: "Fiora",
    value: "Fiora",
    image: { avatar: true, src: "/images/champions/Fiora.png" },
  },
  {
    key: "Fizz",
    text: "Fizz",
    value: "Fizz",
    image: { avatar: true, src: "/images/champions/Fizz.png" },
  },
  {
    key: "Galio",
    text: "Galio",
    value: "Galio",
    image: { avatar: true, src: "/images/champions/Galio.png" },
  },
  {
    key: "Gangplank",
    text: "Gangplank",
    value: "Gangplank",
    image: { avatar: true, src: "/images/champions/Gangplank.png" },
  },
  {
    key: "Garen",
    text: "Garen",
    value: "Garen",
    image: { avatar: true, src: "/images/champions/Garen.png" },
  },
  {
    key: "Gnar",
    text: "Gnar",
    value: "Gnar",
    image: { avatar: true, src: "/images/champions/Gnar.png" },
  },
  {
    key: "Gragas",
    text: "Gragas",
    value: "Gragas",
    image: { avatar: true, src: "/images/champions/Gragas.png" },
  },
  {
    key: "Graves",
    text: "Graves",
    value: "Graves",
    image: { avatar: true, src: "/images/champions/Graves.png" },
  },
  {
    key: "Hecarim",
    text: "Hecarim",
    value: "Hecarim",
    image: { avatar: true, src: "/images/champions/Hecarim.png" },
  },
  {
    key: "Heimerdinger",
    text: "Heimerdinger",
    value: "Heimerdinger",
    image: { avatar: true, src: "/images/champions/Heimerdinger.png" },
  },
  {
    key: "Illaoi",
    text: "Illaoi",
    value: "Illaoi",
    image: { avatar: true, src: "/images/champions/Illaoi.png" },
  },
  {
    key: "Irelia",
    text: "Irelia",
    value: "Irelia",
    image: { avatar: true, src: "/images/champions/Irelia.png" },
  },
  {
    key: "Ivern",
    text: "Ivern",
    value: "Ivern",
    image: { avatar: true, src: "/images/champions/Ivern.png" },
  },
  {
    key: "Janna",
    text: "Janna",
    value: "Janna",
    image: { avatar: true, src: "/images/champions/Janna.png" },
  },
  {
    key: "JarvanIV",
    text: "JarvanIV",
    value: "JarvanIV",
    image: { avatar: true, src: "/images/champions/JarvanIV.png" },
  },
  {
    key: "Jax",
    text: "Jax",
    value: "Jax",
    image: { avatar: true, src: "/images/champions/Jax.png" },
  },
  {
    key: "Jayce",
    text: "Jayce",
    value: "Jayce",
    image: { avatar: true, src: "/images/champions/Jayce.png" },
  },
  {
    key: "Jhin",
    text: "Jhin",
    value: "Jhin",
    image: { avatar: true, src: "/images/champions/Jhin.png" },
  },
  {
    key: "Jinx",
    text: "Jinx",
    value: "Jinx",
    image: { avatar: true, src: "/images/champions/Jinx.png" },
  },
  {
    key: "KaiSa",
    text: "KaiSa",
    value: "KaiSa",
    image: { avatar: true, src: "/images/champions/KaiSa.png" },
  },
  {
    key: "Kalista",
    text: "Kalista",
    value: "Kalista",
    image: { avatar: true, src: "/images/champions/Kalista.png" },
  },
  {
    key: "Karma",
    text: "Karma",
    value: "Karma",
    image: { avatar: true, src: "/images/champions/Karma.png" },
  },
  {
    key: "Karthus",
    text: "Karthus",
    value: "Karthus",
    image: { avatar: true, src: "/images/champions/Karthus.png" },
  },
  {
    key: "Kassadin",
    text: "Kassadin",
    value: "Kassadin",
    image: { avatar: true, src: "/images/champions/Kassadin.png" },
  },
  {
    key: "Katarina",
    text: "Katarina",
    value: "Katarina",
    image: { avatar: true, src: "/images/champions/Katarina.png" },
  },
  {
    key: "Kayle",
    text: "Kayle",
    value: "Kayle",
    image: { avatar: true, src: "/images/champions/Kayle.png" },
  },
  {
    key: "Kayn",
    text: "Kayn",
    value: "Kayn",
    image: { avatar: true, src: "/images/champions/Kayn.png" },
  },
  {
    key: "Kennen",
    text: "Kennen",
    value: "Kennen",
    image: { avatar: true, src: "/images/champions/Kennen.png" },
  },
  {
    key: "KhaZix",
    text: "KhaZix",
    value: "KhaZix",
    image: { avatar: true, src: "/images/champions/KhaZix.png" },
  },
  {
    key: "Kindred",
    text: "Kindred",
    value: "Kindred",
    image: { avatar: true, src: "/images/champions/Kindred.png" },
  },
  {
    key: "Kled",
    text: "Kled",
    value: "Kled",
    image: { avatar: true, src: "/images/champions/Kled.png" },
  },
  {
    key: "KogMaw",
    text: "KogMaw",
    value: "KogMaw",
    image: { avatar: true, src: "/images/champions/KogMaw.png" },
  },
  {
    key: "LeBlanc",
    text: "LeBlanc",
    value: "LeBlanc",
    image: { avatar: true, src: "/images/champions/LeBlanc.png" },
  },
  {
    key: "LeeSin",
    text: "LeeSin",
    value: "LeeSin",
    image: { avatar: true, src: "/images/champions/LeeSin.png" },
  },
  {
    key: "Leona",
    text: "Leona",
    value: "Leona",
    image: { avatar: true, src: "/images/champions/Leona.png" },
  },
  {
    key: "Lissandra",
    text: "Lissandra",
    value: "Lissandra",
    image: { avatar: true, src: "/images/champions/Lissandra.png" },
  },
  {
    key: "Lucian",
    text: "Lucian",
    value: "Lucian",
    image: { avatar: true, src: "/images/champions/Lucian.png" },
  },
  {
    key: "Lulu",
    text: "Lulu",
    value: "Lulu",
    image: { avatar: true, src: "/images/champions/Lulu.png" },
  },
  {
    key: "Lux",
    text: "Lux",
    value: "Lux",
    image: { avatar: true, src: "/images/champions/Lux.png" },
  },
  {
    key: "Malphite",
    text: "Malphite",
    value: "Malphite",
    image: { avatar: true, src: "/images/champions/Malphite.png" },
  },
  {
    key: "Malzahar",
    text: "Malzahar",
    value: "Malzahar",
    image: { avatar: true, src: "/images/champions/Malzahar.png" },
  },
  {
    key: "Maokai",
    text: "Maokai",
    value: "Maokai",
    image: { avatar: true, src: "/images/champions/Maokai.png" },
  },
  {
    key: "MasterYi",
    text: "MasterYi",
    value: "MasterYi",
    image: { avatar: true, src: "/images/champions/MasterYi.png" },
  },
  {
    key: "MissFortune",
    text: "MissFortune",
    value: "MissFortune",
    image: { avatar: true, src: "/images/champions/MissFortune.png" },
  },
  {
    key: "Wukong",
    text: "Wukong",
    value: "Wukong",
    image: { avatar: true, src: "/images/champions/MonkeyKing.png" },
  },
  {
    key: "Mordekaiser",
    text: "Mordekaiser",
    value: "Mordekaiser",
    image: { avatar: true, src: "/images/champions/Mordekaiser.png" },
  },
  {
    key: "Morgana",
    text: "Morgana",
    value: "Morgana",
    image: { avatar: true, src: "/images/champions/Morgana.png" },
  },
  {
    key: "Nami",
    text: "Nami",
    value: "Nami",
    image: { avatar: true, src: "/images/champions/Nami.png" },
  },
  {
    key: "Nasus",
    text: "Nasus",
    value: "Nasus",
    image: { avatar: true, src: "/images/champions/Nasus.png" },
  },
  {
    key: "Nautilus",
    text: "Nautilus",
    value: "Nautilus",
    image: { avatar: true, src: "/images/champions/Nautilus.png" },
  },
  {
    key: "Neeko",
    text: "Neeko",
    value: "Neeko",
    image: { avatar: true, src: "/images/champions/Neeko.png" },
  },
  {
    key: "Nidalee",
    text: "Nidalee",
    value: "Nidalee",
    image: { avatar: true, src: "/images/champions/Nidalee.png" },
  },
  {
    key: "Nocturne",
    text: "Nocturne",
    value: "Nocturne",
    image: { avatar: true, src: "/images/champions/Nocturne.png" },
  },
  {
    key: "NunuWillump",
    text: "NunuWillump",
    value: "NunuWillump",
    image: { avatar: true, src: "/images/champions/Nunu.png" },
  },
  {
    key: "Olaf",
    text: "Olaf",
    value: "Olaf",
    image: { avatar: true, src: "/images/champions/Olaf.png" },
  },
  {
    key: "Orianna",
    text: "Orianna",
    value: "Orianna",
    image: { avatar: true, src: "/images/champions/Orianna.png" },
  },
  {
    key: "Ornn",
    text: "Ornn",
    value: "Ornn",
    image: { avatar: true, src: "/images/champions/Ornn.png" },
  },
  {
    key: "Pantheon",
    text: "Pantheon",
    value: "Pantheon",
    image: { avatar: true, src: "/images/champions/Pantheon.png" },
  },
  {
    key: "Poppy",
    text: "Poppy",
    value: "Poppy",
    image: { avatar: true, src: "/images/champions/Poppy.png" },
  },
  {
    key: "Pyke",
    text: "Pyke",
    value: "Pyke",
    image: { avatar: true, src: "/images/champions/Pyke.png" },
  },
  {
    key: "Qiyana",
    text: "Qiyana",
    value: "Qiyana",
    image: { avatar: true, src: "/images/champions/Qiyana.png" },
  },
  {
    key: "Quinn",
    text: "Quinn",
    value: "Quinn",
    image: { avatar: true, src: "/images/champions/Quinn.png" },
  },
  {
    key: "Rakan",
    text: "Rakan",
    value: "Rakan",
    image: { avatar: true, src: "/images/champions/Rakan.png" },
  },
  {
    key: "Rammus",
    text: "Rammus",
    value: "Rammus",
    image: { avatar: true, src: "/images/champions/Rammus.png" },
  },
  {
    key: "RekSai",
    text: "RekSai",
    value: "RekSai",
    image: { avatar: true, src: "/images/champions/RekSai.png" },
  },
  {
    key: "Renekton",
    text: "Renekton",
    value: "Renekton",
    image: { avatar: true, src: "/images/champions/Renekton.png" },
  },
  {
    key: "Rengar",
    text: "Rengar",
    value: "Rengar",
    image: { avatar: true, src: "/images/champions/Rengar.png" },
  },
  {
    key: "Riven",
    text: "Riven",
    value: "Riven",
    image: { avatar: true, src: "/images/champions/Riven.png" },
  },
  {
    key: "Rumble",
    text: "Rumble",
    value: "Rumble",
    image: { avatar: true, src: "/images/champions/Rumble.png" },
  },
  {
    key: "Ryze",
    text: "Ryze",
    value: "Ryze",
    image: { avatar: true, src: "/images/champions/Ryze.png" },
  },
  {
    key: "Sejuani",
    text: "Sejuani",
    value: "Sejuani",
    image: { avatar: true, src: "/images/champions/Sejuani.png" },
  },
  {
    key: "Senna",
    text: "Senna",
    value: "Senna",
    image: { avatar: true, src: "/images/champions/Senna.png" },
  },
  {
    key: "Sett",
    text: "Sett",
    value: "Sett",
    image: { avatar: true, src: "/images/champions/Sett.png" },
  },
  {
    key: "Shaco",
    text: "Shaco",
    value: "Shaco",
    image: { avatar: true, src: "/images/champions/Shaco.png" },
  },
  {
    key: "Shen",
    text: "Shen",
    value: "Shen",
    image: { avatar: true, src: "/images/champions/Shen.png" },
  },
  {
    key: "Shyvana",
    text: "Shyvana",
    value: "Shyvana",
    image: { avatar: true, src: "/images/champions/Shyvana.png" },
  },
  {
    key: "Singed",
    text: "Singed",
    value: "Singed",
    image: { avatar: true, src: "/images/champions/Singed.png" },
  },
  {
    key: "Sion",
    text: "Sion",
    value: "Sion",
    image: { avatar: true, src: "/images/champions/Sion.png" },
  },
  {
    key: "Sivir",
    text: "Sivir",
    value: "Sivir",
    image: { avatar: true, src: "/images/champions/Sivir.png" },
  },
  {
    key: "Skarner",
    text: "Skarner",
    value: "Skarner",
    image: { avatar: true, src: "/images/champions/Skarner.png" },
  },
  {
    key: "Sona",
    text: "Sona",
    value: "Sona",
    image: { avatar: true, src: "/images/champions/Sona.png" },
  },
  {
    key: "Soraka",
    text: "Soraka",
    value: "Soraka",
    image: { avatar: true, src: "/images/champions/Soraka.png" },
  },
  {
    key: "Swain",
    text: "Swain",
    value: "Swain",
    image: { avatar: true, src: "/images/champions/Swain.png" },
  },
  {
    key: "Sylas",
    text: "Sylas",
    value: "Sylas",
    image: { avatar: true, src: "/images/champions/Sylas.png" },
  },
  {
    key: "Syndra",
    text: "Syndra",
    value: "Syndra",
    image: { avatar: true, src: "/images/champions/Syndra.png" },
  },
  {
    key: "TahmKench",
    text: "TahmKench",
    value: "TahmKench",
    image: { avatar: true, src: "/images/champions/TahmKench.png" },
  },
  {
    key: "Taliyah",
    text: "Taliyah",
    value: "Taliyah",
    image: { avatar: true, src: "/images/champions/Taliyah.png" },
  },
  {
    key: "Talon",
    text: "Talon",
    value: "Talon",
    image: { avatar: true, src: "/images/champions/Talon.png" },
  },
  {
    key: "Taric",
    text: "Taric",
    value: "Taric",
    image: { avatar: true, src: "/images/champions/Taric.png" },
  },
  {
    key: "Teemo",
    text: "Teemo",
    value: "Teemo",
    image: { avatar: true, src: "/images/champions/Teemo.png" },
  },
  {
    key: "Thresh",
    text: "Thresh",
    value: "Thresh",
    image: { avatar: true, src: "/images/champions/Thresh.png" },
  },
  {
    key: "Tristana",
    text: "Tristana",
    value: "Tristana",
    image: { avatar: true, src: "/images/champions/Tristana.png" },
  },
  {
    key: "Trundle",
    text: "Trundle",
    value: "Trundle",
    image: { avatar: true, src: "/images/champions/Trundle.png" },
  },
  {
    key: "Tryndamere",
    text: "Tryndamere",
    value: "Tryndamere",
    image: { avatar: true, src: "/images/champions/Tryndamere.png" },
  },
  {
    key: "TwistedFate",
    text: "TwistedFate",
    value: "TwistedFate",
    image: { avatar: true, src: "/images/champions/TwistedFate.png" },
  },
  {
    key: "Twitch",
    text: "Twitch",
    value: "Twitch",
    image: { avatar: true, src: "/images/champions/Twitch.png" },
  },
  {
    key: "Udyr",
    text: "Udyr",
    value: "Udyr",
    image: { avatar: true, src: "/images/champions/Udyr.png" },
  },
  {
    key: "Urgot",
    text: "Urgot",
    value: "Urgot",
    image: { avatar: true, src: "/images/champions/Urgot.png" },
  },
  {
    key: "Varus",
    text: "Varus",
    value: "Varus",
    image: { avatar: true, src: "/images/champions/Varus.png" },
  },
  {
    key: "Vayne",
    text: "Vayne",
    value: "Vayne",
    image: { avatar: true, src: "/images/champions/Vayne.png" },
  },
  {
    key: "Veigar",
    text: "Veigar",
    value: "Veigar",
    image: { avatar: true, src: "/images/champions/Veigar.png" },
  },
  {
    key: "VelKoz",
    text: "VelKoz",
    value: "VelKoz",
    image: { avatar: true, src: "/images/champions/VelKoz.png" },
  },
  {
    key: "Vi",
    text: "Vi",
    value: "Vi",
    image: { avatar: true, src: "/images/champions/Vi.png" },
  },
  {
    key: "Viktor",
    text: "Viktor",
    value: "Viktor",
    image: { avatar: true, src: "/images/champions/Viktor.png" },
  },
  {
    key: "Vladimir",
    text: "Vladimir",
    value: "Vladimir",
    image: { avatar: true, src: "/images/champions/Vladimir.png" },
  },
  {
    key: "Volibear",
    text: "Volibear",
    value: "Volibear",
    image: { avatar: true, src: "/images/champions/Volibear.png" },
  },
  {
    key: "Warwick",
    text: "Warwick",
    value: "Warwick",
    image: { avatar: true, src: "/images/champions/Warwick.png" },
  },
  {
    key: "Xayah",
    text: "Xayah",
    value: "Xayah",
    image: { avatar: true, src: "/images/champions/Xayah.png" },
  },
  {
    key: "Xerath",
    text: "Xerath",
    value: "Xerath",
    image: { avatar: true, src: "/images/champions/Xerath.png" },
  },
  {
    key: "XinZhao",
    text: "XinZhao",
    value: "XinZhao",
    image: { avatar: true, src: "/images/champions/XinZhao.png" },
  },
  {
    key: "Yasuo",
    text: "Yasuo",
    value: "Yasuo",
    image: { avatar: true, src: "/images/champions/Yasuo.png" },
  },
  {
    key: "Yorick",
    text: "Yorick",
    value: "Yorick",
    image: { avatar: true, src: "/images/champions/Yorick.png" },
  },
  {
    key: "Yuumi",
    text: "Yuumi",
    value: "Yuumi",
    image: { avatar: true, src: "/images/champions/Yuumi.png" },
  },
  {
    key: "Zac",
    text: "Zac",
    value: "Zac",
    image: { avatar: true, src: "/images/champions/Zac.png" },
  },
  {
    key: "Zed",
    text: "Zed",
    value: "Zed",
    image: { avatar: true, src: "/images/champions/Zed.png" },
  },
  {
    key: "Ziggs",
    text: "Ziggs",
    value: "Ziggs",
    image: { avatar: true, src: "/images/champions/Ziggs.png" },
  },
  {
    key: "Zilean",
    text: "Zilean",
    value: "Zilean",
    image: { avatar: true, src: "/images/champions/Zilean.png" },
  },
  {
    key: "Zoe",
    text: "Zoe",
    value: "Zoe",
    image: { avatar: true, src: "/images/champions/Zoe.png" },
  },
  {
    key: "Zyra",
    text: "Zyra",
    value: "Zyra",
    image: { avatar: true, src: "/images/champions/Zyra.png" },
  },
];
