// Contains all the form values specific to each image
export const roleOptions = [
  {
    key: "Top",
    text: "Top",
    value: "Top",
    image: { avatar: true, src: "/images/roles/top.png" },
  },
  {
    key: "Jungle",
    text: "Jungle",
    value: "Jungle",
    image: { avatar: true, src: "/images/roles/jungle.png" },
  },
  {
    key: "Mid",
    text: "Mid",
    value: "Mid",
    image: { avatar: false, src: "/images/roles/mid.png" },
  },
  {
    key: "Support",
    text: "Support",
    value: "Support",
    image: { avatar: true, src: "/images/roles/support.png" },
  },
  {
    key: "Bot",
    text: "Bot",
    value: "Bot",
    image: { avatar: true, src: "/images/roles/bot.png" },
  },
];

export const championOptions = [
  {
    key: "Aatrox",
    text: "Aatrox",
    value: "Aatrox",
    image: { avatar: true, src: "/images/champions/aatrox.png" },
  },
  {
    key: "Ahri",
    text: "Ahri",
    value: "Ahri",
    image: { avatar: true, src: "/images/champions/ahri.png" },
  },
  {
    key: "Akali",
    text: "Akali",
    value: "Akali",
    image: { avatar: true, src: "/images/champions/akali.png" },
  },
  {
    key: "Alistar",
    text: "Alistar",
    value: "Alistar",
    image: { avatar: true, src: "/images/champions/alistar.png" },
  },
  {
    key: "Amumu",
    text: "Amumu",
    value: "Amumu",
    image: { avatar: true, src: "/images/champions/amumu.png" },
  },
  {
    key: "Anivia",
    text: "Anivia",
    value: "Anivia",
    image: { avatar: true, src: "/images/champions/anivia.png" },
  },
  {
    key: "Annie",
    text: "Annie",
    value: "Annie",
    image: { avatar: true, src: "/images/champions/annie.png" },
  },
  {
    key: "Aphelios",
    text: "Aphelios",
    value: "Aphelios",
    image: { avatar: true, src: "/images/champions/aphelios.png" },
  },
  {
    key: "Ashe",
    text: "Ashe",
    value: "Ashe",
    image: { avatar: true, src: "/images/champions/ashe.png" },
  },
  {
    key: "AurelionSol",
    text: "AurelionSol",
    value: "AurelionSol",
    image: { avatar: true, src: "/images/champions/aurelionsol.png" },
  },
  {
    key: "Azir",
    text: "Azir",
    value: "Azir",
    image: { avatar: true, src: "/images/champions/azir.png" },
  },
  {
    key: "Bard",
    text: "Bard",
    value: "Bard",
    image: { avatar: true, src: "/images/champions/bard.png" },
  },
  {
    key: "Blitzcrank",
    text: "Blitzcrank",
    value: "Blitzcrank",
    image: { avatar: true, src: "/images/champions/blitzcrank.png" },
  },
  {
    key: "Brand",
    text: "Brand",
    value: "Brand",
    image: { avatar: true, src: "/images/champions/brand.png" },
  },
  {
    key: "Braum",
    text: "Braum",
    value: "Braum",
    image: { avatar: true, src: "/images/champions/braum.png" },
  },
  {
    key: "Caitlyn",
    text: "Caitlyn",
    value: "Caitlyn",
    image: { avatar: true, src: "/images/champions/caitlyn.png" },
  },
  {
    key: "Camille",
    text: "Camille",
    value: "Camille",
    image: { avatar: true, src: "/images/champions/camille.png" },
  },
  {
    key: "Cassiopeia",
    text: "Cassiopeia",
    value: "Cassiopeia",
    image: { avatar: true, src: "/images/champions/cassiopeia.png" },
  },
  {
    key: "ChoGath",
    text: "ChoGath",
    value: "ChoGath",
    image: { avatar: true, src: "/images/champions/chogath.png" },
  },
  {
    key: "Corki",
    text: "Corki",
    value: "Corki",
    image: { avatar: true, src: "/images/champions/corki.png" },
  },
  {
    key: "Darius",
    text: "Darius",
    value: "Darius",
    image: { avatar: true, src: "/images/champions/darius.png" },
  },
  {
    key: "Diana",
    text: "Diana",
    value: "Diana",
    image: { avatar: true, src: "/images/champions/diana.png" },
  },
  {
    key: "Draven",
    text: "Draven",
    value: "Draven",
    image: { avatar: true, src: "/images/champions/draven.png" },
  },
  {
    key: "DrMundo",
    text: "DrMundo",
    value: "DrMundo",
    image: { avatar: true, src: "/images/champions/drmundo.png" },
  },
  {
    key: "Ekko",
    text: "Ekko",
    value: "Ekko",
    image: { avatar: true, src: "/images/champions/ekko.png" },
  },
  {
    key: "Elise",
    text: "Elise",
    value: "Elise",
    image: { avatar: true, src: "/images/champions/elise.png" },
  },
  {
    key: "Evelynn",
    text: "Evelynn",
    value: "Evelynn",
    image: { avatar: true, src: "/images/champions/evelynn.png" },
  },
  {
    key: "Ezreal",
    text: "Ezreal",
    value: "Ezreal",
    image: { avatar: true, src: "/images/champions/ezreal.png" },
  },
  {
    key: "Fiddlesticks",
    text: "Fiddlesticks",
    value: "Fiddlesticks",
    image: { avatar: true, src: "/images/champions/fiddlesticks.png" },
  },
  {
    key: "Fiora",
    text: "Fiora",
    value: "Fiora",
    image: { avatar: true, src: "/images/champions/fiora.png" },
  },
  {
    key: "Fizz",
    text: "Fizz",
    value: "Fizz",
    image: { avatar: true, src: "/images/champions/fizz.png" },
  },
  {
    key: "Galio",
    text: "Galio",
    value: "Galio",
    image: { avatar: true, src: "/images/champions/galio.png" },
  },
  {
    key: "Gangplank",
    text: "Gangplank",
    value: "Gangplank",
    image: { avatar: true, src: "/images/champions/gangplank.png" },
  },
  {
    key: "Garen",
    text: "Garen",
    value: "Garen",
    image: { avatar: true, src: "/images/champions/garen.png" },
  },
  {
    key: "Gnar",
    text: "Gnar",
    value: "Gnar",
    image: { avatar: true, src: "/images/champions/gnar.png" },
  },
  {
    key: "Gragas",
    text: "Gragas",
    value: "Gragas",
    image: { avatar: true, src: "/images/champions/gragas.png" },
  },
  {
    key: "Graves",
    text: "Graves",
    value: "Graves",
    image: { avatar: true, src: "/images/champions/graves.png" },
  },
  {
    key: "Hecarim",
    text: "Hecarim",
    value: "Hecarim",
    image: { avatar: true, src: "/images/champions/hecarim.png" },
  },
  {
    key: "Heimerdinger",
    text: "Heimerdinger",
    value: "Heimerdinger",
    image: { avatar: true, src: "/images/champions/heimerdinger.png" },
  },
  {
    key: "Illaoi",
    text: "Illaoi",
    value: "Illaoi",
    image: { avatar: true, src: "/images/champions/illaoi.png" },
  },
  {
    key: "Irelia",
    text: "Irelia",
    value: "Irelia",
    image: { avatar: true, src: "/images/champions/irelia.png" },
  },
  {
    key: "Ivern",
    text: "Ivern",
    value: "Ivern",
    image: { avatar: true, src: "/images/champions/ivern.png" },
  },
  {
    key: "Janna",
    text: "Janna",
    value: "Janna",
    image: { avatar: true, src: "/images/champions/janna.png" },
  },
  {
    key: "JarvanIV",
    text: "JarvanIV",
    value: "JarvanIV",
    image: { avatar: true, src: "/images/champions/jarvaniv.png" },
  },
  {
    key: "Jax",
    text: "Jax",
    value: "Jax",
    image: { avatar: true, src: "/images/champions/jax.png" },
  },
  {
    key: "Jayce",
    text: "Jayce",
    value: "Jayce",
    image: { avatar: true, src: "/images/champions/jayce.png" },
  },
  {
    key: "Jhin",
    text: "Jhin",
    value: "Jhin",
    image: { avatar: true, src: "/images/champions/jhin.png" },
  },
  {
    key: "Jinx",
    text: "Jinx",
    value: "Jinx",
    image: { avatar: true, src: "/images/champions/jinx.png" },
  },
  {
    key: "KaiSa",
    text: "KaiSa",
    value: "KaiSa",
    image: { avatar: true, src: "/images/champions/kaisa.png" },
  },
  {
    key: "Kalista",
    text: "Kalista",
    value: "Kalista",
    image: { avatar: true, src: "/images/champions/kalista.png" },
  },
  {
    key: "Karma",
    text: "Karma",
    value: "Karma",
    image: { avatar: true, src: "/images/champions/karma.png" },
  },
  {
    key: "Karthus",
    text: "Karthus",
    value: "Karthus",
    image: { avatar: true, src: "/images/champions/karthus.png" },
  },
  {
    key: "Kassadin",
    text: "Kassadin",
    value: "Kassadin",
    image: { avatar: true, src: "/images/champions/kassadin.png" },
  },
  {
    key: "Katarina",
    text: "Katarina",
    value: "Katarina",
    image: { avatar: true, src: "/images/champions/katarina.png" },
  },
  {
    key: "Kayle",
    text: "Kayle",
    value: "Kayle",
    image: { avatar: true, src: "/images/champions/kayle.png" },
  },
  {
    key: "Kayn",
    text: "Kayn",
    value: "Kayn",
    image: { avatar: true, src: "/images/champions/kayn.png" },
  },
  {
    key: "Kennen",
    text: "Kennen",
    value: "Kennen",
    image: { avatar: true, src: "/images/champions/kennen.png" },
  },
  {
    key: "KhaZix",
    text: "KhaZix",
    value: "KhaZix",
    image: { avatar: true, src: "/images/champions/khazix.png" },
  },
  {
    key: "Kindred",
    text: "Kindred",
    value: "Kindred",
    image: { avatar: true, src: "/images/champions/kindred.png" },
  },
  {
    key: "Kled",
    text: "Kled",
    value: "Kled",
    image: { avatar: true, src: "/images/champions/kled.png" },
  },
  {
    key: "KogMaw",
    text: "KogMaw",
    value: "KogMaw",
    image: { avatar: true, src: "/images/champions/kogmaw.png" },
  },
  {
    key: "LeBlanc",
    text: "LeBlanc",
    value: "LeBlanc",
    image: { avatar: true, src: "/images/champions/leblanc.png" },
  },
  {
    key: "LeeSin",
    text: "LeeSin",
    value: "LeeSin",
    image: { avatar: true, src: "/images/champions/leesin.png" },
  },
  {
    key: "Leona",
    text: "Leona",
    value: "Leona",
    image: { avatar: true, src: "/images/champions/leona.png" },
  },
  {
    key: "Lissandra",
    text: "Lissandra",
    value: "Lissandra",
    image: { avatar: true, src: "/images/champions/lissandra.png" },
  },
  {
    key: "Lucian",
    text: "Lucian",
    value: "Lucian",
    image: { avatar: true, src: "/images/champions/lucian.png" },
  },
  {
    key: "Lulu",
    text: "Lulu",
    value: "Lulu",
    image: { avatar: true, src: "/images/champions/lulu.png" },
  },
  {
    key: "Lux",
    text: "Lux",
    value: "Lux",
    image: { avatar: true, src: "/images/champions/lux.png" },
  },
  {
    key: "Malphite",
    text: "Malphite",
    value: "Malphite",
    image: { avatar: true, src: "/images/champions/malphite.png" },
  },
  {
    key: "Malzahar",
    text: "Malzahar",
    value: "Malzahar",
    image: { avatar: true, src: "/images/champions/malzahar.png" },
  },
  {
    key: "Maokai",
    text: "Maokai",
    value: "Maokai",
    image: { avatar: true, src: "/images/champions/maokai.png" },
  },
  {
    key: "MasterYi",
    text: "MasterYi",
    value: "MasterYi",
    image: { avatar: true, src: "/images/champions/masteryi.png" },
  },
  {
    key: "MissFortune",
    text: "MissFortune",
    value: "MissFortune",
    image: { avatar: true, src: "/images/champions/missfortune.png" },
  },
  {
    key: "Wukong",
    text: "Wukong",
    value: "Wukong",
    image: { avatar: true, src: "/images/champions/wukong.png" },
  },
  {
    key: "Mordekaiser",
    text: "Mordekaiser",
    value: "Mordekaiser",
    image: { avatar: true, src: "/images/champions/mordekaiser.png" },
  },
  {
    key: "Morgana",
    text: "Morgana",
    value: "Morgana",
    image: { avatar: true, src: "/images/champions/morgana.png" },
  },
  {
    key: "Nami",
    text: "Nami",
    value: "Nami",
    image: { avatar: true, src: "/images/champions/nami.png" },
  },
  {
    key: "Nasus",
    text: "Nasus",
    value: "Nasus",
    image: { avatar: true, src: "/images/champions/nasus.png" },
  },
  {
    key: "Nautilus",
    text: "Nautilus",
    value: "Nautilus",
    image: { avatar: true, src: "/images/champions/nautilus.png" },
  },
  {
    key: "Neeko",
    text: "Neeko",
    value: "Neeko",
    image: { avatar: true, src: "/images/champions/neeko.png" },
  },
  {
    key: "Nidalee",
    text: "Nidalee",
    value: "Nidalee",
    image: { avatar: true, src: "/images/champions/nidalee.png" },
  },
  {
    key: "Nocturne",
    text: "Nocturne",
    value: "Nocturne",
    image: { avatar: true, src: "/images/champions/nocturne.png" },
  },
  {
    key: "NunuWillump",
    text: "NunuWillump",
    value: "NunuWillump",
    image: { avatar: true, src: "/images/champions/nunuwillump.png" },
  },
  {
    key: "Olaf",
    text: "Olaf",
    value: "Olaf",
    image: { avatar: true, src: "/images/champions/olaf.png" },
  },
  {
    key: "Orianna",
    text: "Orianna",
    value: "Orianna",
    image: { avatar: true, src: "/images/champions/orianna.png" },
  },
  {
    key: "Ornn",
    text: "Ornn",
    value: "Ornn",
    image: { avatar: true, src: "/images/champions/ornn.png" },
  },
  {
    key: "Pantheon",
    text: "Pantheon",
    value: "Pantheon",
    image: { avatar: true, src: "/images/champions/pantheon.png" },
  },
  {
    key: "Poppy",
    text: "Poppy",
    value: "Poppy",
    image: { avatar: true, src: "/images/champions/poppy.png" },
  },
  {
    key: "Pyke",
    text: "Pyke",
    value: "Pyke",
    image: { avatar: true, src: "/images/champions/pyke.png" },
  },
  {
    key: "Qiyana",
    text: "Qiyana",
    value: "Qiyana",
    image: { avatar: true, src: "/images/champions/qiyana.png" },
  },
  {
    key: "Quinn",
    text: "Quinn",
    value: "Quinn",
    image: { avatar: true, src: "/images/champions/quinn.png" },
  },
  {
    key: "Rakan",
    text: "Rakan",
    value: "Rakan",
    image: { avatar: true, src: "/images/champions/rakan.png" },
  },
  {
    key: "Rammus",
    text: "Rammus",
    value: "Rammus",
    image: { avatar: true, src: "/images/champions/rammus.png" },
  },
  {
    key: "RekSai",
    text: "RekSai",
    value: "RekSai",
    image: { avatar: true, src: "/images/champions/reksai.png" },
  },
  {
    key: "Renekton",
    text: "Renekton",
    value: "Renekton",
    image: { avatar: true, src: "/images/champions/renekton.png" },
  },
  {
    key: "Rengar",
    text: "Rengar",
    value: "Rengar",
    image: { avatar: true, src: "/images/champions/rengar.png" },
  },
  {
    key: "Riven",
    text: "Riven",
    value: "Riven",
    image: { avatar: true, src: "/images/champions/riven.png" },
  },
  {
    key: "Rumble",
    text: "Rumble",
    value: "Rumble",
    image: { avatar: true, src: "/images/champions/rumble.png" },
  },
  {
    key: "Ryze",
    text: "Ryze",
    value: "Ryze",
    image: { avatar: true, src: "/images/champions/ryze.png" },
  },
  {
    key: "Sejuani",
    text: "Sejuani",
    value: "Sejuani",
    image: { avatar: true, src: "/images/champions/sejuani.png" },
  },
  {
    key: "Senna",
    text: "Senna",
    value: "Senna",
    image: { avatar: true, src: "/images/champions/senna.png" },
  },
  {
    key: "Sett",
    text: "Sett",
    value: "Sett",
    image: { avatar: true, src: "/images/champions/sett.png" },
  },
  {
    key: "Shaco",
    text: "Shaco",
    value: "Shaco",
    image: { avatar: true, src: "/images/champions/shaco.png" },
  },
  {
    key: "Shen",
    text: "Shen",
    value: "Shen",
    image: { avatar: true, src: "/images/champions/shen.png" },
  },
  {
    key: "Shyvana",
    text: "Shyvana",
    value: "Shyvana",
    image: { avatar: true, src: "/images/champions/shyvana.png" },
  },
  {
    key: "Singed",
    text: "Singed",
    value: "Singed",
    image: { avatar: true, src: "/images/champions/singed.png" },
  },
  {
    key: "Sion",
    text: "Sion",
    value: "Sion",
    image: { avatar: true, src: "/images/champions/sion.png" },
  },
  {
    key: "Sivir",
    text: "Sivir",
    value: "Sivir",
    image: { avatar: true, src: "/images/champions/sivir.png" },
  },
  {
    key: "Skarner",
    text: "Skarner",
    value: "Skarner",
    image: { avatar: true, src: "/images/champions/skarner.png" },
  },
  {
    key: "Sona",
    text: "Sona",
    value: "Sona",
    image: { avatar: true, src: "/images/champions/sona.png" },
  },
  {
    key: "Soraka",
    text: "Soraka",
    value: "Soraka",
    image: { avatar: true, src: "/images/champions/soraka.png" },
  },
  {
    key: "Swain",
    text: "Swain",
    value: "Swain",
    image: { avatar: true, src: "/images/champions/swain.png" },
  },
  {
    key: "Sylas",
    text: "Sylas",
    value: "Sylas",
    image: { avatar: true, src: "/images/champions/sylas.png" },
  },
  {
    key: "Syndra",
    text: "Syndra",
    value: "Syndra",
    image: { avatar: true, src: "/images/champions/syndra.png" },
  },
  {
    key: "TahmKench",
    text: "TahmKench",
    value: "TahmKench",
    image: { avatar: true, src: "/images/champions/tahmkench.png" },
  },
  {
    key: "Taliyah",
    text: "Taliyah",
    value: "Taliyah",
    image: { avatar: true, src: "/images/champions/taliyah.png" },
  },
  {
    key: "Talon",
    text: "Talon",
    value: "Talon",
    image: { avatar: true, src: "/images/champions/talon.png" },
  },
  {
    key: "Taric",
    text: "Taric",
    value: "Taric",
    image: { avatar: true, src: "/images/champions/taric.png" },
  },
  {
    key: "Teemo",
    text: "Teemo",
    value: "Teemo",
    image: { avatar: true, src: "/images/champions/teemo.png" },
  },
  {
    key: "Thresh",
    text: "Thresh",
    value: "Thresh",
    image: { avatar: true, src: "/images/champions/thresh.png" },
  },
  {
    key: "Tristana",
    text: "Tristana",
    value: "Tristana",
    image: { avatar: true, src: "/images/champions/tristana.png" },
  },
  {
    key: "Trundle",
    text: "Trundle",
    value: "Trundle",
    image: { avatar: true, src: "/images/champions/trundle.png" },
  },
  {
    key: "Tryndamere",
    text: "Tryndamere",
    value: "Tryndamere",
    image: { avatar: true, src: "/images/champions/tryndamere.png" },
  },
  {
    key: "TwistedFate",
    text: "TwistedFate",
    value: "TwistedFate",
    image: { avatar: true, src: "/images/champions/twistedfate.png" },
  },
  {
    key: "Twitch",
    text: "Twitch",
    value: "Twitch",
    image: { avatar: true, src: "/images/champions/twitch.png" },
  },
  {
    key: "Udyr",
    text: "Udyr",
    value: "Udyr",
    image: { avatar: true, src: "/images/champions/udyr.png" },
  },
  {
    key: "Urgot",
    text: "Urgot",
    value: "Urgot",
    image: { avatar: true, src: "/images/champions/urgot.png" },
  },
  {
    key: "Varus",
    text: "Varus",
    value: "Varus",
    image: { avatar: true, src: "/images/champions/varus.png" },
  },
  {
    key: "Vayne",
    text: "Vayne",
    value: "Vayne",
    image: { avatar: true, src: "/images/champions/vayne.png" },
  },
  {
    key: "Veigar",
    text: "Veigar",
    value: "Veigar",
    image: { avatar: true, src: "/images/champions/veigar.png" },
  },
  {
    key: "VelKoz",
    text: "VelKoz",
    value: "VelKoz",
    image: { avatar: true, src: "/images/champions/velkoz.png" },
  },
  {
    key: "Vi",
    text: "Vi",
    value: "Vi",
    image: { avatar: true, src: "/images/champions/vi.png" },
  },
  {
    key: "Viktor",
    text: "Viktor",
    value: "Viktor",
    image: { avatar: true, src: "/images/champions/viktor.png" },
  },
  {
    key: "Vladimir",
    text: "Vladimir",
    value: "Vladimir",
    image: { avatar: true, src: "/images/champions/vladimir.png" },
  },
  {
    key: "Volibear",
    text: "Volibear",
    value: "Volibear",
    image: { avatar: true, src: "/images/champions/volibear.png" },
  },
  {
    key: "Warwick",
    text: "Warwick",
    value: "Warwick",
    image: { avatar: true, src: "/images/champions/warwick.png" },
  },
  {
    key: "Xayah",
    text: "Xayah",
    value: "Xayah",
    image: { avatar: true, src: "/images/champions/xayah.png" },
  },
  {
    key: "Xerath",
    text: "Xerath",
    value: "Xerath",
    image: { avatar: true, src: "/images/champions/xerath.png" },
  },
  {
    key: "XinZhao",
    text: "XinZhao",
    value: "XinZhao",
    image: { avatar: true, src: "/images/champions/xinzhao.png" },
  },
  {
    key: "Yasuo",
    text: "Yasuo",
    value: "Yasuo",
    image: { avatar: true, src: "/images/champions/yasuo.png" },
  },
  {
    key: "Yorick",
    text: "Yorick",
    value: "Yorick",
    image: { avatar: true, src: "/images/champions/yorick.png" },
  },
  {
    key: "Yuumi",
    text: "Yuumi",
    value: "Yuumi",
    image: { avatar: true, src: "/images/champions/yuumi.png" },
  },
  {
    key: "Zac",
    text: "Zac",
    value: "Zac",
    image: { avatar: true, src: "/images/champions/zac.png" },
  },
  {
    key: "Zed",
    text: "Zed",
    value: "Zed",
    image: { avatar: true, src: "/images/champions/zed.png" },
  },
  {
    key: "Ziggs",
    text: "Ziggs",
    value: "Ziggs",
    image: { avatar: true, src: "/images/champions/ziggs.png" },
  },
  {
    key: "Zilean",
    text: "Zilean",
    value: "Zilean",
    image: { avatar: true, src: "/images/champions/zilean.png" },
  },
  {
    key: "Zoe",
    text: "Zoe",
    value: "Zoe",
    image: { avatar: true, src: "/images/champions/zoe.png" },
  },
  {
    key: "Zyra",
    text: "Zyra",
    value: "Zyra",
    image: { avatar: true, src: "/images/champions/zyra.png" },
  },
];
